version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ebs-snapshot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wwnww46dhckk"
s3_prefix = "ebs-snapshot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
